apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodeapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodeapp
    app.kubernetes.io/part-of: test-application
  name: nodeapp
  namespace: karthik-jk
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nodeapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nodeapp
    spec:
      containers:
      - image: quay.io/karthik_jk/nodeapp@sha256:6c7b007f7fb9d500e306fb8e4ef416cf0a46d7da46b54492507e5047405d3544
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
