apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodeapp
  namespace: karthik-jk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: env
          value: development
        image: quay.io/karthik_jk/nodeapp@sha256:5a7aa6f50e85c97b656a057bfb64510a65a2f2fddcc1b010e3e1b937dc2ba9ae
        name: container-image
        resources: {}
status: {}
